apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../mps

patches:
  - path: patch-device-plugin-config.yaml
    target:
      kind: ConfigMap
      name: device-plugin-config
