apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: sdxl-http
spec:
  name: "SDXL Serving Runtime"
  systemName: "sdxl-http"
  privateBaseURL: "http://sdxl-predictor.llm-hosting.svc.cluster.local:8080"