apiVersion: v1
kind: Namespace
metadata:
  name: evalhub-tenant
  labels:
    evalhub.trustyai.opendatahub.io/tenant: "true"
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "4"
