kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: cert-manager-operator

resources:
  - openshift-wildcard-certificate.yaml
  - patch-cluster-wildcard-cert-job.yaml
  - patch-cluster-wildcard-cert-cronjob.yaml
