apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: autoscaling.openshift.io
      kind: ClusterAutoscaler
      name: default
    patch: |-
      - op: remove
        path: /spec/resourceLimits/maxNodesTotal
      - op: remove
        path: /spec/resourceLimits/cores
      - op: remove
        path: /spec/resourceLimits/memory
      - op: replace
        path: /spec/resourceLimits/gpus/0/max
        value: 4
      - op: replace
        path: /spec/scaleDown/delayAfterAdd
        value: 20m
      - op: replace
        path: /spec/scaleDown/delayAfterDelete
        value: 5m
      - op: remove
        path: /spec/scaleDown/utilizationThreshold