apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../base

patches:
  - path: patch-region.yaml
    target:
      kind: ClusterSecretStore
      name: rhoaibu-external-store
