apiVersion: v1
kind: ConfigMap
metadata:
  name: device-plugin-config
data:
  no-mps-sliced: |-
    version: v1
    sharing:
      mps:
        resources:
          - name: nvidia.com/gpu
            replicas: 0
