apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: kuadrant-prometheus-datasource
  namespace: redhat-ods-applications
  annotations:
    opendatahub.io/managed: "false"
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    app.kubernetes.io/component: perses
    app.kubernetes.io/managed-by: maas-observability
    app.opendatahub.io/modelsasservice: "true"
    platform.opendatahub.io/part-of: modelsasservice
spec:
  client:
    tls:
      caCert:
        certPath: service-ca.crt
        name: prometheus-web-tls-ca
        type: configmap
      enable: true
  config:
    default: false
    display:
      name: Prometheus (Thanos Querier)
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            secret: kuadrant-prometheus-datasource-secret
            url: https://thanos-querier.openshift-monitoring.svc:9092?namespace=kuadrant-system
        scrapeInterval: 30s
