apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: starburst-enterprise-helm-operator-rhmp
    path: patch-channel.yaml
