apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  kustomizeBuildOptions: '--enable-helm'
  initialRepositories: |
    - url: https://github.com/rh-aiservices-bu/rh-aiservices-bu-bootstrap.git
      type: git
      passwordSecret:
        key: password
        name: git-auth
      usernameSecret:
        key: username
        name: git-auth
