apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - model-registry-db-parameters.yaml
  - model-registry-secret.yaml
  - model-registry.yaml
  - mysql-deployment.yaml
  - mysql-pvc.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
  - rolebinding.yaml