---
apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/description: 'Model Registry'
    openshift.io/display-name: registry
  name: registry
  namespace: rhoai-model-registries
spec:
  grpc:
    port: 9090
  mysql:
    database: metadb
    host: registry-db.rhoai-model-registries.svc.cluster.local
    passwordSecret:
      key: database-password
      name: registry-db
    port: 3306
    username: root
  oauthProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  rest:
    port: 8080
    serviceRoute: disabled
