
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-db-parameters
  namespace: rhoai-model-registries
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  MYSQL_DATABASE: metadb
  MYSQL_PORT: '3306'
