---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-db
  namespace: rhoai-model-registries
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rhoaibu-external-store
    kind: ClusterSecretStore
  target:
    name: registry-db
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: model-registries-db-credentials
        property: database-password
    - secretKey: database-user
      remoteRef:
        key: model-registries-db-credentials
        property: database-user
    - secretKey: database-name
      remoteRef:
        key: model-registries-db-credentials
        property: database-name
