apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../aws-node-labeler

patches:
  - patch: |-
      - op: replace
        path: /parameters/region
        value: us-west-2
    target:
      kind: StorageClass
      name: ocs-storagecluster-ceph-rgw
