apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- with .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
