apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - ../../base
  - storagecluster.yaml
  - gp3-remove-default.yaml
  - ceph-rbd-set-default.yaml
