apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog/kiali-operator/overlays/stable?ref=main

patches:
  - target:
      kind: Subscription
      name: kiali-ossm
    path: patch-channel.yaml
