apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-gpu-operator

resources:
  - job.yaml

helmCharts:
  - name: console-plugin-nvidia-gpu
    releaseName: console-plugin-nvidia-gpu
    # namespace: nvidia-gpu-operator
    repo: https://rh-ecosystem-edge.github.io/console-plugin-nvidia-gpu

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-gpu-console-plugin
    files:
      - job.sh
