kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  components:
    codeflare:
      devFlags: {}
      managementState: Managed
    dashboard:
      devFlags: {}
      managementState: Managed
    datasciencepipelines:
      devFlags: {}
      managementState: Managed
    kserve:
      devFlags: {}
      managementState: Managed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headless
      serving:
        ingressGateway:
          certificate:
            type: OpenshiftDefaultIngress
        managementState: Managed
        name: knative-serving
    modelmeshserving:
      devFlags: {}
      managementState: Managed
    ray:
      devFlags: {}
      managementState: Managed
    trustyai:
      managementState: Managed
    workbenches:
      managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    llamastackoperator:
      managementState: Managed
    feastoperator:
      managementState: Managed
    kueue:
      managementState: Managed
    trainingoperator:
      managementState: Managed