apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - datasciencecluster.yaml
  - odh-dashboard-config.yaml
  - notebook-controller-culler-config-cm.yaml
  - accelerator-profile.yaml
