kind: ConfigMap
apiVersion: v1
metadata:
  name: notebook-controller-culler-config
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  CULL_IDLE_TIME: "180"
  ENABLE_CULLING: "true"
  IDLENESS_CHECK_PERIOD: "1"
