apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - rbac-for-authenticated-users.yaml

patches:
  - target:
      kind: OLSConfig
      name: cluster
    path: maas-mistral.yaml
