---
apiVersion: capabilities.3scale.net/v1beta1
kind: ProxyConfigPromote
metadata:
  name: deepseek-r1-qwen-14b-w4a16
spec:
  productCRName: deepseek-r1-qwen-14b-w4a16
  production: true
  deleteCR: false