apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: large-gpu-card
  namespace: redhat-ods-applications
spec:
  description: 'Restricted use - Do not select without approval'
  displayName: Large GPU Card (NVIDIA A10G - 24 GB VRAM)
  enabled: false
  identifier: nvidia.com/gpu
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      value: NVIDIA-A10G-SHARED
