apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: very-large-gpu-card
  namespace: redhat-ods-applications
spec:
  description: 'Restricted use - Do not select without approval'
  displayName: Very Large GPU Card (NVIDIA A100 - 40 GB VRAM)
  enabled: false
  identifier: nvidia.com/gpu
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      value: NVIDIA-A100-SHARED
