apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog/serverless-operator/operator/overlays/stable-1.30?ref=main

patches:
  - target:
      kind: Subscription
      name: serverless-operator
    path: patch-channel.yaml
