apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: starburst-enterprise-helm-operator-rhmp
  namespace: openshift-operators
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: starburst-enterprise-helm-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
