apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: worker-gpu-g6.2xlarge-us-east-1a
  namespace: openshift-machine-api
spec:
  maxReplicas: 2
  minReplicas: 0
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: worker-gpu-g6.2xlarge-us-east-1a