apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default
spec:
  components:
    codeflare:
      managementState: Managed
    ray:
      managementState: Managed
    kueue:
      managementState: Managed
