apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog/gpu-operator-certified/operator/overlays/stable?ref=main

patches:
  - target:
      kind: Subscription
      name: gpu-operator-certified
    path: patch-channel.yaml
