apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - subscription.yaml
  - operatorgroup.yaml

patches:
  - target:
      kind: Subscription
      name: lightspeed-operator
    path: patch-channel.yaml
