apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/compare-options: IgnoreExtraneous

patches:
  - target:
      group: nfd.openshift.io
      kind: NodeFeatureDiscovery
    path: patch-node-feature-discovery.yaml
