apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: qwen25-vl-7b-instruct
spec:
  name: "Qwen2.5-VL-7B-Instruct"
  systemName: "qwen25-vl-7b-instruct"
  privateBaseURL: "http://qwen25-vl-7b-instruct-fp8-dynamic-predictor.llm-hosting.svc.cluster.local:8080"
