apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: DataScienceCluster
      name: default-dsc
    patch: |-
      - op: replace
        path: /spec/components/kserve/modelsAsService/managementState
        value: Managed
