- op: replace
  path: /spec/template/spec/source/targetRevision
  value: dev # Adjust it to the desired branch for Dev (main)
- op: replace
  path: /spec/generators/0/list/elements/1/values/path
  value: components/configs/console/overlays/rhoaibu-cluster-dev
