---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Mistral-Small-24B-W8A8
    serving.kserve.io/deploymentMode: RawDeployment
  name: mistral-small-24b-w8a8
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--model=/mnt/models'
        - '--served-model-name=mistral-small-24b-w8a8'
        - '--max-model-len=90000'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser'
        - 'mistral'
        - '--chat-template'
        - '/app/data/template/tool_chat_template_mistral_parallel.jinja'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '6'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '4'
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: vllm-rhoai-2.21
      storage:
        key: aws-connection-models
        path: RedHatAI/Mistral-Small-3.1-24B-Instruct-2503-quantized.w8a8/
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: NVIDIA-L40S-PRIVATE