---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    opendatahub.io/model-type: generative
    openshift.io/description: ''
    openshift.io/display-name: qwen25-vl-7b-instruct
    security.opendatahub.io/enable-auth: 'false'
    serving.kserve.io/deploymentMode: Standard
  name: qwen25-vl-7b-instruct
  namespace: llm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name=RedHatAI/Qwen2.5-VL-7B-Instruct-FP8-Dynamic'
        - '--distributed-executor-backend=mp'
        - '--dtype=auto'
        - '--max-model-len=100000'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '4'
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: vllm-rhoai-2.21
      storageUri: 'pvc://models/RedHatAI/Qwen2.5-VL-7B-Instruct-FP8-Dynamic'
    timeout: 600
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: NVIDIA-L40-PRIVATE
