apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: nomic-embed-text-v1-5
spec:
  name: "Nomic-Embed-Text-v1.5"
  systemName: nomic-embed-text-v1-5
  privateBaseURL: "http://nomic-embed-text-v1-5-predictor.llm-hosting.svc.cluster.local:8080"
